import React, { useState, useContext, useEffect } from "react";
import PriceCard from "../components/cards/PriceCard";
import axios from "axios";
import { UserContext } from "../context";


const Home = () => {
  const [state, setState] = useContext(UserContext);

  useEffect(()=>{
    console.log('***', state)
  },[state])

  useEffect(()=>{
    fetchAccount()
  },[])

  const fetchAccount = async () => {
    const { data } = await axios.get("/get-subscription", {
      params: {
        email: 'nav@gmail.com'
      } 
    });
    console.log({data})
  }

  const handleRequest = async (amount,plan) => {
    debugger
    try {
      const { data } = await axios.post("/create-subscription", {
        email: state?.user?.email, // Send any required data to the backend
        amount,
        plan,
      });
      // Create a form and append the necessary fields
      const form = document.createElement('form');
      form.method = 'POST';
      form.action = data.url; // URL generated by the server
      form.target = '_blank'; // Open in a new window/tab

      // Add form fields dynamically
      Object.keys(data.fields).forEach((key) => {
        const input = document.createElement('input');
        input.type = 'hidden';
        input.name = key;
        input.value = data.fields[key];
        form.appendChild(input);
      });

      // Append the form to the body and submit it
      document.body.appendChild(form);
      form.submit();
    } catch (error) {
      console.error("Error during payment process:", error);
    }
  };

  return (
    <div className="container-fluid">
      <div className="row col-md-6 offset-md-3 text-center">
        <h1 className="pt-5 fw-bold">SpectraIQ Pricing Plan</h1>
        <p className="lead pb-4">Choose a plan that suits you best!</p>
      </div>
      <div className="row pt-5 mb-3 text-center">
        <PriceCard 
        handleRequest={handleRequest}
        amount = {"20.00"}
        plan={"BASIC"}
        head_1 = {"5 Dashboards"}
        />
          <PriceCard 
        handleRequest={handleRequest}
        amount = {"50.00"}
        plan={"STANDARD"}  
        head_1 = {"15 Dashboards"}
        />
         <PriceCard 
        handleRequest={handleRequest}
        amount = {"100.00"}
        plan={"PREMIUM"}   
        head_1 = {"25 Dashboards"}
        />
      </div>
     
    </div>
  );
};

export default Home;
