import PriceCard from "../components/cards/PriceCard";
import axios from "axios";

const Home = () => {
  const handleRequest = async (e) => {
    e.preventDefault();
    try {
      const { data } = await axios.post("/create-subscription", {
        email: "john@example.com", // Send any required data to the backend
      });
      console.log('data', data);

      // Create a form and append the necessary fields
      const form = document.createElement('form');
      form.method = 'POST';
      form.action = data.url; // URL generated by the server
      form.target = '_blank'; // Open in a new window/tab

      // Add form fields dynamically
      Object.keys(data.fields).forEach((key) => {
        const input = document.createElement('input');
        input.type = 'hidden';
        input.name = key;
        input.value = data.fields[key];
        form.appendChild(input);
      });

      // Append the form to the body and submit it
      document.body.appendChild(form);
      form.submit();
    } catch (error) {
      console.error("Error during payment process:", error);
    }
  };

  return (
    <div className="container-fluid">
      <div className="row col-md-6 offset-md-3 text-center">
        <h1 className="pt-5 fw-bold">Explore the right plan for your business</h1>
        <p className="lead pb-4">Choose a plan that suits you best!</p>
      </div>
      <div className="row pt-5 mb-3 text-center">
        <PriceCard handleRequest={handleRequest} />
      </div>
    </div>
  );
};

export default Home;
